//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADMIN_GUI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADS
    {
        public int ID { get; set; }
        public string CONTENT { get; set; }
        public System.DateTime DATE_OF_CREATE { get; set; }
        public int STUDENT_ID { get; set; }
    
        public virtual STUDENT STUDENT { get; set; }
    }
}
