//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STUDENT_GUI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LESSON
    {
        public int ID { get; set; }
        public Nullable<int> LESSON_DAY { get; set; }
        public Nullable<int> LESSON_NUMBER { get; set; }
        public string LESSON_TIME { get; set; }
        public string LESSON_TYPE { get; set; }
        public string LESSON_WEEK { get; set; }
        public string AUDITORIUM { get; set; }
        public Nullable<int> SUBJECT_ID { get; set; }
        public int GROUP_ID { get; set; }
        public int SUBGROUP_ID { get; set; }
    
        public virtual GROUP GROUP { get; set; }
        public virtual SUBGROUP SUBGROUP { get; set; }
        public virtual SUBJECT SUBJECT { get; set; }
    }
}
