//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STUDENT_GUI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROGRESS
    {
        public int ID { get; set; }
        public int NEEDED_TASKS { get; set; }
        public int COMPLITED_TASKS { get; set; }
        public Nullable<int> PROGRESS_COUNT { get; set; }
        public int SUBJECT_ID { get; set; }
        public int STUDENT_ID { get; set; }
    
        public virtual STUDENT STUDENT { get; set; }
        public virtual SUBJECT SUBJECT { get; set; }
    }
}
